INSERT INTO law_schools (school, personal_statement, diversity_statement, optional_statement_prompt, letters_of_recommendation, resume, extras_addenda, application_fee, interviews, note)
VALUES 
('Harvard Law School', 
 'Please submit a personal statement of 2 pages discussing your background and interests.', 
 'Optional: Submit a diversity statement explaining how you would contribute to the diversity of the law school community.', 
 'Optional: You may submit an additional statement about your interest in Harvard Law School.', 
 'Three letters of recommendation required.', 
 'Submit a current resume or CV.', 
 'You may submit addenda explaining any circumstances in your application.', 
 '$85', 
 'Interviews are by invitation only.', 
 'Early Decision deadline: November 15'),

('Yale Law School',
 'Submit a personal statement of no more than 4 pages double-spaced.',
 'Optional: Submit a diversity statement of 1-2 pages.',
 'Optional: 250-word essay on any subject of your choice.',
 'At least two letters of recommendation required, preferably three.',
 'Submit a current resume.',
 'Character and fitness addendum if applicable.',
 '$85',
 'Interviews are by invitation only after application review.',
 'Regular decision deadline: February 15'),

('Stanford Law School',
 'Personal statement should be no more than 2 pages double-spaced.',
 'Optional: Statement about your background and diversity.',
 'Optional: Why Stanford essay of 100-250 words.',
 'Two to four letters of recommendation.',
 'One-page resume required.',
 'Optional addenda for any additional information.',
 '$85',
 'Selected candidates may be invited for interviews.',
 'Applications accepted from September 15');
