/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d3ad389e-63f2-4287-84f0-88630cbf6cc5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_oxI8fl1uF",
    "aws_user_pools_web_client_id": "4qaconh7k500foaq4b2ki6690l",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_oxI8fl1uF",
        "userPoolWebClientId": "4qaconh7k500foaq4b2ki6690l"
    }
};


export default awsmobile;
